name: Compile DTS to DTB

on: 
  #workflow_dispatch
  schedule:
   - cron:  '10 5 * * *'

permissions:
  contents: write

env:
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0
  LINUX_AMLOGIC_GIT: https://github.com/CoreELEC/linux-amlogic.git
  COMMON_DRIVERS_GIT: https://github.com/CoreELEC/common_drivers.git
  LINUX_AMLOGIC_ROOT: /tmp/linux-amlogic
  COMMON_DRIVERS_ROOT: /tmp/linux-amlogic/common_drivers
  DTS_ROOT: /tmp/linux-amlogic/common_drivers/arch/
  RELEASE_NOTES: /tmp/releasenotes
  RELEASE_ZIP: /tmp/coreelec_dts_dtb.zip
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        $APT update
        $APT install fd-find autoconf build-essential bc bison flex device-tree-compiler
    
    - name: Set up environment
      run: |
        cd /tmp/
        RELEASE_NAME="$(date '+%Y%m%d%H%m%S')"
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
        
        git clone -q --depth=1 "$LINUX_AMLOGIC_GIT" "$LINUX_AMLOGIC_ROOT"
        
        cd "$LINUX_AMLOGIC_ROOT"        
        git clone -q --depth=1 "$COMMON_DRIVERS_GIT" "$COMMON_DRIVERS_ROOT"
        
        ls -al "$LINUX_AMLOGIC_ROOT"
        ls -al "$COMMON_DRIVERS_ROOT"
        
        du -sh "$LINUX_AMLOGIC_ROOT"
        du -sh "$COMMON_DRIVERS_ROOT"

    - name: Show versions
      run: |
        cd "$LINUX_AMLOGIC_ROOT"
        echo -e "linux-amlogic:\t$(git branch --show current)" | tee -a "$RELEASE_NOTES"
        
        cd "$COMMON_DRIVERS_ROOT"
        echo -e "common_drivers:\t$(git branch --show current)" | tee -a "$RELEASE_NOTES"

    - name: Make DTBs
      run: |
        cd "$LINUX_AMLOGIC_ROOT"
        make -j$(nproc) ARCH=arm64 defconfig && make -j$(nproc) ARCH=arm64 dtbs
        make -j$(nproc) ARCH=arm defconfig && make -j$(nproc) ARCH=arm dtbs
        make -j$(nproc) ARCH=riscv defconfig && make -j$(nproc) ARCH=riscv dtbs

    - name: Concatenate full DTSs
      run: |
        cd /tmp/
        fdfind -e dts . "$DTS_ROOT" -x cpp -nostdinc -undef -x assembler-with-cpp -I "$LINUX_AMLOGIC_ROOT/include" -I "$COMMON_DRIVERS_ROOT/include" -o "{.}_full.dts" "{}" || true

    - name: Decompile the compiled DTBs
      run: |
        cd /tmp/
        fdfind -e dtb . "$DTS_ROOT" -x dtc -q -I dtb -O dts -o "{.}_decompiled.dts" "{}"
    
    - name: List files
      run: |
        cd /tmp/
        fdfind -e dts -e dtb . "$DTS_ROOT" | sort

    - name: Add to ZIP
      run: |
        cd "$COMMON_DRIVERS_ROOT"
        fdfind -e dts -e dtb . | sort | zip -9 -q -o "$RELEASE_ZIP" -@

        cd $(dirname "$RELEASE_ZIP")
        sha256sum --tag $(basename "$RELEASE_ZIP") | tee -a "$RELEASE_NOTES"
        ls -alh "$RELEASE_ZIP"

    - name: Create a new Github release
      uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda #v3.0.1
      with:
        make_latest: true
        body_path: ${{ env.RELEASE_NOTES }}
        name: version ${{ env.RELEASE_NAME }}
        tag_name: v${{ env.RELEASE_NAME }}
        files: |
          ${{ env.RELEASE_ZIP }}
